language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

addons:
  chrome: stable

dist: trusty

sudo: required

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - vendor
    - node_modules

before_script:
  - cp .env.travis.example .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan telescope:install
  - php artisan migrate
  - npm install --no-audit --no-progress --quiet
  - yarn production

before_install:
  - mysql -e 'CREATE DATABASE homestead;'
  - travis_retry composer self-update && composer --version
  - nvm install --lts
  - npm i -g yarn

script:
  - phpunit

notifications:
  email: false
