language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

dist: trusty

sudo: required

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - vendor
    - node_modules

before_install:
  - mysql -e 'CREATE DATABASE homestead;'
  - travis_retry composer self-update && composer --version
  - nvm install --lts
  - npm i -g npm

install:
  - cp .env.travis.example .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan telescope:install
  - php artisan migrate
  - npm install --silent --non-interactive
  - npm run production

script:
  - composer test

notifications:
  email: false
